learning_log1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'',include('learning_log1s.urls', namespace='learning_log1s')),
    
]
app_name = 'learning_log1s'

learning_log1s/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
app_name='learning_log1s'

urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/(?P<topic_id>\d+)/', views.topic, name='topic'),
]

    

learning_log1s/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
  text = models.CharField(max_length=200)
  data_added = models.DateTimeField(auto_now_add=True)
  def __str__(self):
    return  self.text
    
class Entry(models.Model):
  topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
  text = models.TextField()
  data_added = models.TimeField(auto_now_add=True)
  class Meta:
    verbose_name_plural = 'entries'

  def __str__(self):
    return  self.text[:50]+ "..."

learning_log1s/views.py
from django.shortcuts import render

from .models import Topic

# Create your views here.
def index(request):
  return render(request,'learning_log1s/index.html')

def topics(request):
  topics = Topic.objects.order_by('data_added')
  context = {'topics': topics}
  return render(request, 'learning_log1s/topics.html',context)

def topic(request, topic_id):
  topic = Topic.objects.get(id=topic_id)
  entries = topic.entry_set.order_by('-data_added')
  context = {'topic': topic, 'entries': entries}
  return render(request, 'learning_log1s/topic.html',context)

learning_log1s/templates/learning_log1s/base.html
<p>
    <a href="{% url 'learning_log1s:index' %}">learning_log1</a>
    <a href="{% url 'learning_log1s:topics' %}">Topics</a>
</p>

{% block content %}{% endblock content %}

learning_log1s/templates/learning_log1s/index.html
{% extends "learning_log1s/base.html" %}

{% block content %}
<p>Learning Log helps you track of your learning.</p>
{% endblock content %}

learning_log1s/templates/learning_log1s/topic.html
{% extends 'learning_log1s/base.html' %}
{% block content %}

  <p>Topic:{{topic}}</p>

  <p>Entries:</p>
  <ul>
  {% for entry in entries %}
    <li>
      <p>{{entry.data_added|date:'M d, Y H:i'}}</p>
      <p>{{entry.text|linebreaks}}</p>
    </li>  
  {% empty %}
    <li>
      There are no entries for this topic yet. 
    </li>
  {% endfor %}
  </ul>

{% endblock content %}

learning_log1s/templates/learning_log1s/topics.html
{% extends "learning_log1s/base.html" %}

{% block content %}

  <p>Topics</p>

  <ul>
    {% for topic in topics %}
      <li>
        <a href ="{% url 'learning_log1s:topic' topic.id %}">{{topic}}</a>
      </li>
    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>

{% endblock content %}